--For manual reset
--DROP TABLE IF EXISTS users;
--DROP TABLE IF EXISTS items;

CREATE TABLE IF NOT EXISTS users (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS items (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    list_name VARCHAR(255) NOT NULL,
    description TEXT,
    author_name VARCHAR(255),
    importance SMALLINT
);